const $ = id => document.getElementById(id);
let questions = [], session = [], pos = 0, mode = 'learn', lang = localStorage.lang || 'ua', answers = {};
const copy = {
  ua:{empty:'Тут поки немає питань', correct:'Правильно ✅', wrong:'Неправильно ❌', next:'Далі', finish:'Завершити', back:'Назад', menu:'← Меню', result:'Твій результат', answered:'Відповіли', stats:'Статистика', reset:'Прогрес скинуто'},
  en:{empty:'No questions here yet', correct:'Correct ✅', wrong:'Wrong ❌', next:'Next', finish:'Finish', back:'Back', menu:'← Menu', result:'Your result', answered:'Answered', stats:'Statistics', reset:'Progress reset'},
  ru:{empty:'Пока здесь нет вопросов', correct:'Правильно ✅', wrong:'Неправильно ❌', next:'Далее', finish:'Завершить', back:'Назад', menu:'← Меню', result:'Твой результат', answered:'Ответили', stats:'Статистика', reset:'Прогресс сброшен'}
};
function get(k, fallback){try{return JSON.parse(localStorage[k]||fallback)}catch{return JSON.parse(fallback)}}
function set(k,v){localStorage[k]=JSON.stringify(v)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
async function init(){questions=await fetch('questions.json').then(r=>r.json());$('totalCount').textContent=questions.length;$('lang').value=lang;if(localStorage.theme==='dark')document.body.classList.add('dark');bind();}
function bind(){document.querySelectorAll('.mode-card').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('lang').onchange=e=>{lang=e.target.value;localStorage.lang=lang;render()};$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};$('resetBtn').onclick=()=>{if(confirm('Скинути прогрес?')){['wrong','fav','seen','correct'].forEach(k=>localStorage.removeItem(k));alert(copy[lang].reset)}};$('backBtn').onclick=home;$('homeBtn').onclick=home;$('statsHomeBtn').onclick=home;$('prevBtn').onclick=()=>{if(pos>0){pos--;render()}};$('nextBtn').onclick=()=>pos<session.length-1?(pos++,render()):finish();$('favBtn').onclick=toggleFav;}
function start(m){mode=m;if(m==='stats')return showStats();answers={};const wrong=get('wrong','[]'), fav=get('fav','[]');if(m==='learn')session=[...questions];if(m==='random')session=shuffle(questions);if(m==='exam')session=shuffle(questions).slice(0,40);if(m==='wrong')session=questions.filter(q=>wrong.includes(q.id));if(m==='fav')session=questions.filter(q=>fav.includes(q.id));if(!session.length){alert(copy[lang].empty);return}pos=0;show('quiz');render();}
function show(id){['home','quiz','result','stats'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.querySelector('.controls').classList.toggle('hidden',id!=='home')}
function home(){show('home')}
function imageFor(q){return q.image || `images/${q.id}.png`}
function render(){if($('quiz').classList.contains('hidden'))return;const q=session[pos], c=copy[lang];$('qid').textContent=`№ ${q.id}`;$('counter').textContent=`${pos+1} / ${session.length}`;$('modeLabel').textContent=mode.toUpperCase();$('bar').style.width=`${(pos+1)/session.length*100}%`;$('question').textContent=q.question?.[lang] || q.question?.en || '';
 const img=$('qImg'); img.classList.add('hidden'); img.onerror=()=>{ if(img.dataset.tryroot!=='1'){img.dataset.tryroot='1'; img.src=`${q.id}.png`;} else img.classList.add('hidden')}; img.onload=()=>img.classList.remove('hidden'); img.dataset.tryroot='0'; img.src=imageFor(q);
 const fav=get('fav','[]');$('favBtn').textContent=fav.includes(q.id)?'★':'☆';$('answers').innerHTML='';q.options.forEach((opt,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=opt?.[lang]||opt?.en||'';b.onclick=()=>choose(i);if(answers[q.id]!==undefined){if(i===q.correctIndex)b.classList.add('correct');if(i===answers[q.id]&&i!==q.correctIndex)b.classList.add('wrong')} $('answers').appendChild(b)});$('feedback').className='feedback hidden';if(answers[q.id]!==undefined){const ok=answers[q.id]===q.correctIndex;$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=ok?c.correct:`${c.wrong} Правильна: ${q.options[q.correctIndex]?.[lang]||q.options[q.correctIndex]?.en||''}`}$('prevBtn').textContent=c.back;$('nextBtn').textContent=pos===session.length-1?c.finish:c.next;$('backBtn').textContent=c.menu;}
function choose(i){const q=session[pos];answers[q.id]=i;const wrong=new Set(get('wrong','[]')), seen=new Set(get('seen','[]')), correct=new Set(get('correct','[]'));seen.add(q.id);if(i===q.correctIndex){wrong.delete(q.id);correct.add(q.id)}else{wrong.add(q.id);correct.delete(q.id)}set('wrong',[...wrong]);set('seen',[...seen]);set('correct',[...correct]);render();}
function toggleFav(){const q=session[pos];const fav=new Set(get('fav','[]'));fav.has(q.id)?fav.delete(q.id):fav.add(q.id);set('fav',[...fav]);render();}
function finish(){const correct=session.filter(q=>answers[q.id]===q.correctIndex).length, answered=Object.keys(answers).length;show('result');$('resultText').textContent=`${copy[lang].result}: ${correct} / ${session.length}. ${copy[lang].answered}: ${answered}.`;const wrong=session.filter(q=>answers[q.id]!==undefined&&answers[q.id]!==q.correctIndex).slice(0,12);$('resultList').innerHTML=wrong.map(q=>`<div class="mini">№${q.id} ${q.question?.[lang]||q.question?.en||''}</div>`).join('');}
function showStats(){show('stats');const seen=get('seen','[]').length, wrong=get('wrong','[]').length, fav=get('fav','[]').length, correct=get('correct','[]').length;$('statsText').innerHTML=`Пройдено: <b>${seen}</b> / ${questions.length}<br>Правильно зараз: <b>${correct}</b><br>Помилки: <b>${wrong}</b><br>Обране: <b>${fav}</b>`;}
init();
